config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ventas/', include('ventas.urls')),
    path('inventario/', include('inventario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import signin, inicio

app_name = 'core'

urlpatterns = [
    path('', signin, name='signin'),
    path('inicio/', inicio, name='inicio'),   
]

ventas/urls.py
from django.urls import path
from .views import ventas, registrar_venta, listar_ventas, registrar_venta_copy
from . import views

app_name = 'ventas'

urlpatterns = [
    path('', ventas, name='ventas'),
    path('registrar/', registrar_venta, name='registrar_venta'),
    path('listar/', listar_ventas, name='listar_ventas'),
    path('registrar-copy/', registrar_venta_copy, name='registrar_venta_copy'),
]

ventas/models.py
from django.db import models
from django.conf import settings
# from django.contrib.auth import get_user_model
# from django.contrib.auth.models import User


# Create your models here.
class Venta(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    fecha_venta = models.DateTimeField(auto_now_add=True)
    monto_total = models.DecimalField(max_digits=10, decimal_places=2)
    metodo_pago = models.CharField(max_length=50, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')])
    monto_pagado = models.DecimalField(max_digits=10, decimal_places=2)
    cambio = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    # idcliente = models.ForeignKey('clientes.Cliente', on_delete=models.CASCADE, null=True, blank=True)
    productos = models.ManyToManyField('inventario.Producto', through='DetalleVenta')

    def __str__(self):
        return f"Venta {self.id} - Total: {self.total}"
    
class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey('inventario.Producto', on_delete=models.CASCADE)
    precio_unitario = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad = models.PositiveIntegerField()

    def __str__(self):
        return f"Detalle de Venta {self.venta.id} - Producto: {self.producto.nombre}"

ventas/forms.py
from django import forms
from .models import Venta

class VentaForm(forms.ModelForm):
    class Meta:
        model = Venta
        fields = ['metodo_pago', 'monto_pagado']
        widgets = {
            'metodo_pago': forms.Select(attrs={'class': 'form-control'}),
            'monto_pagado': forms.NumberInput(attrs={'class': 'form-control', 'step': '0.01'}),
        }
        labels = {
            'metodo_pago': 'Método de Pago',
            'monto_pagado': 'Monto Pagado',
        }

ventas/views.py
from django.shortcuts import render
from inventario.models import Producto
from ventas.models import Venta, DetalleVenta
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
import json
from .forms import VentaForm
from django.shortcuts import render

# Create your views here.
def ventas(request):
    return render(request, 'ventas/ventas.html')

def listar_ventas(request):
    return render(request, 'ventas/listar_ventas.html', {
        'ventas': Venta.objects.all()
        })

def registrar_venta(request):
    if request.method == "POST":
        form = VentaForm(request.POST)
        if form.is_valid():
            try:
                # Guardar la venta
                venta = form.save(commit=False)
                venta.usuario = request.user
                venta.monto_total = request.POST.get('total', 0)
                venta.monto_pagado = request.POST.get('monto_pagado', 0)
                venta.cambio = float(venta.monto_pagado) - float(venta.monto_total)
                venta.save()

                # Guardar los detalles de la venta
                productos_ids = json.loads(request.POST.get('productos', '[]'))
                for producto_id in productos_ids:
                    producto = Producto.objects.get(idproducto=producto_id)
                    DetalleVenta.objects.create(
                        venta=venta,
                        producto=producto,
                        precio_unitario=producto.precio,
                        cantidad=1 # Ajustar según sea necesario
                    )

                return JsonResponse({"status": "success", "message": "Venta registrada exitosamente."})
            except Exception as e:
                return JsonResponse({"status": "error", "message": str(e)})
        else:
            return JsonResponse({"status": "error", "message": f"Formulario inválido. {str(e)}"})
    else:
        form = VentaForm()
        return render(request, 'ventas/registrar_venta.html', {
            'productos': Producto.objects.all(),
            'form': form
        })
    

def registrar_venta_copy(request):
    if request.method == "POST":
        try:
            # Obtener los datos enviados desde fetch()
            productos = json.loads(request.POST.get("productos", "[]"))
            total = float(request.POST.get("total", 0))

            venta = Venta.objects.create(
                monto_total=total,
                monto_pagado=total,
                cambio=0,
            )

            # Crear los detalles de la venta
            for producto in productos:
                producto_obj = Producto.objects.get(idproducto=producto["id"])
                DetalleVenta.objects.create(
                    venta=venta,
                    producto=producto_obj,
                    cantidad=producto["cantidad"],
                    precio_unitario=producto["precio"]
                )

            return JsonResponse({"status": "success", "message": "Venta registrada exitosamente."})
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)})
    else:
        return render(request, 'ventas/registrar_venta_copy.html')

ventas/templates/ventas/listar_ventas.html
{% extends 'base.html' %}

{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="{% static 'ventas/css/listar_ventas.css' %}">
{% endblock extra_head %}

{% block title %}Ventas{% endblock title %}

{% block content %}
<h1>Ventas</h1>

<div class="barra_sup">
  <input type="text" id="search" placeholder="Buscar venta...">
</div>

<div class="table_container">
  <table>
    <colgroup>
      <col style="width: 3%">
      <col style="width: 10%">
      <col>
      <col style="width: 7%">
      <col>
      <col style="width: 7%">
      <col style="width: 7%">

    </colgroup>
    <thead>
      <tr>
        <th>ID</th>
        <th>Usuario responsable</th>
        <th>Fecha</th>
        <th>Monto Total</th>
        <th>Método de pago</th>
        <th>Monto Pagado</th>
        <th>Cambio Entregado</th>
        <th>Productos</th>
        {% comment %} <th>Detalles</th> {% endcomment %}
        {% comment %} <th>Cliente</th> {% endcomment %}
      </tr>
    </thead>
    <tbody id="ventas_table_body">
      {% for venta in ventas %}
      <tr class="venta" data-id="{{ venta.id }}">
        <td>{{ venta.id }}</td>
        <td>{{ venta.usuario.username }}</td>
        {% comment %} <td>{{ venta.cliente }}</td> {% endcomment %}
        <td>{{ venta.fecha_venta }}</td>
        <td>${{ venta.monto_total }}</td>
        <td>{{ venta.metodo_pago }}</td>
        <td>${{ venta.monto_pagado }}</td>
        <td>${{ venta.cambio }}</td>
        <td>
          <ul class="productos">
            {% for producto in venta.productos.all %}
            <li>{{ producto.nombre }}</li>
            {% endfor %}
          </ul>
        </td>
        {% comment %} <td><a href="{% url 'ventas:detalles_venta' venta.id %}">Ver Detalles</a></td> {% endcomment %}
      </tr>
  
      {% empty %}
      <tr>
        <td colspan="8" class="no_products">No hay ventas registradas.</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

{% block scripts %}
<script src="{% static 'ventas/js/buscador_ventas.js' %}"></script>
{% endblock scripts %}

ventas/templates/ventas/registrar_venta.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'ventas/css/reg_venta.css' %}">
{% endblock extra_head %}

{% block title %}Ventas{% endblock title %}

{% block content %}

<h1>Registrar Venta</h1>
<div class="buscador">
  <input type="text" id="search" placeholder="Buscar producto...">
</div>

<div class="productos_container">
  
  {% for producto in productos %}
  <div class="producto" data-id="{{ producto.idproducto }}" id="prod_{{ producto.idproducto }}">
    <img src="{{ producto.imagen.url }}" width="200">
    <h3>{{ producto.nombre }}</h3>
    <p>Precio: ${{ producto.precio }}</p>
  </div>
  {% empty %}
  <div class="no_products">Es necesario registrar productos en el inventario.</div>
  {% endfor %}
    
</div>

<div class="bottom">
  <div id="venta_container" class="venta_container">
    <button id="btn_registrar_venta">Registrar venta</button>
    <p id="total_text">Total: $0.00</p>
  </div>
</div>

<!-- filepath: c:\Users\steme\OneDrive\Documents\Sexto Semestre\Metodologías del Desarrollo de Software\PIA\Spartan-Gym\ventas\templates\ventas\registrar_venta.html -->
<div class="venta_modal" id="venta_modal">
  <h2>Registrar Venta</h2>
  <form id="venta_form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p id="cambio_text">Cambio: </p>
    <button type="button" id="confirmar_venta">Confirmar Venta</button>
    <button type="button" id="cancelar_venta">Cancelar</button>
  </form>
</div>
<div class="modal_overlay" id="modal_overlay"></div>
{% endblock content %}



{% block scripts %}
<script>
  const registrarVentaUrl = "{% url 'ventas:registrar_venta' %}";
</script>
<script src="{% static 'ventas/js/registrar_venta.js' %}"></script>
{% endblock scripts %}

ventas/templates/ventas/registrar_venta_copy.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'ventas/css/reg_venta_copy.css' %}">
{% endblock extra_head %}


{% block content %}

<h1>Registrar Venta</h1>

<div class="buscador">
  <input type="text" id="search" placeholder="Buscar producto...">
</div>

<div class="productos_container">
  <div class="productos">
    <div class="producto" data-id="1" data-precio="16499">
      <img src="{% static 'img/laptop_inspiron.jpg' %}" alt="">
      <h3>Laptop Dell Inspiron 15</h3>
      <p>
        <b>Descripción:</b> Computadora portátil con procesador Intel Core i5 de 12ª
        generación, 16 GB de RAM, SSD de 512 GB y pantalla Full HD de
        15.6”.
      </p>
      <p>
        <b>Garantía:</b> 4 años
      </p>
      <p><b>Precio:</b> $16,499 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
  
  <div class="productos">
    <div class="producto" data-id="2" data-precio="2199">
      <img src="{% static 'img/router.jpg' %}" alt="">
      <h3>Router TP-Link AX1800</h3>
      <p>
        <b>Descripción:</b> Router de doble banda con tecnología Wi-Fi 6.
      <p><b>Conectividad:</b> Wi-Fi, USB</p>
      <p><b>Compatibilidad:</b> Windows, macOS, Android, iOS</p>
  
      <p>
        <b>Garantía:</b> 1 año
      </p>
      <p><b>Precio:</b> $2,199 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
  
  <div class="productos">
    <div class="producto" data-id="3" data-precio="1899">
      <img src="{% static 'img/discoduro.jpg' %}" alt="">
      <h3>Disco Duro Externo 2TB</h3>
      <p>
        <b>Descripción:</b>Almacenamiento portátil USB 3.0, perfecto para respaldos y
        transferencia de grandes volúmenes de información.
      </p>
      <p><b>Compatibilidad:</b> Windows, macOS, Android, iOS</p>
  
      <p>
        <b>Garantía:</b> 1 año
      </p>
      <p><b>Precio:</b> $1,899 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
  
  <div class="productos">
    <div class="producto" data-id="4" data-precio="20999">
      <img src="{% static 'img/monitor.jpg' %}" alt="">
      <h3>Monitor LG 24” Full HD</h3>
      <p>
        <b>Descripción:</b> Monitor IPS con resolución 1920x1080. Incluye puertos HDMI y VGA
      </p>
      <p>
        <b>Garantía:</b> 5 año
      </p>
      <p><b>Precio:</b> $20,999 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
  
  <div class="productos">
    <div class="producto" data-id="5" data-precio="3299">
      <img src="{% static 'img/kit.jpg' %}" alt="">
      <h3>Kit de Teclado y Mouse Inalámbrico Logitech</h3>
      <p>
        <b>Descripción:</b> Kit ergonómico con conectividad inalámbrica, silencioso y de larga
        duración de batería.
  
      </p>
      <p><b>Conectividad:</b> USB</p>
      <p><b>Compatibilidad:</b> Windows y macOS</p>
  
      <p>
        <b>Garantía:</b> 1 año
      </p>
      <p><b>Precio:</b> $3,299 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
  
  <div class="productos">
    <div class="producto" data-id="6" data-precio="5000">
      <img src="{% static 'img/audifonos.jpg' %}" alt="">
      <h3>Audífonos con micrófono Jabra</h3>
      <p>
        <b>Descripción:</b> Audífonos profesionales con cancelación de ruido y micrófono
        integrado
      </p>
      <p><b>Conectividad:</b> USB, Bluetooth</p>
      <p><b>Compatibilidad:</b> Windows, macOS, Android, iOS</p>
  
      <p>
        <b>Garantía:</b> 1 año
      </p>
      <p><b>Precio:</b> $5,000 MXN</p>
      <div class="cantidad-control">
        <button class="restar">−</button>
        <span class="cantidad">0</span>
        <button class="sumar">+</button>
      </div>
    </div>
  </div>
</div>

<div class="bottom">
  <div id="venta_container" class="venta_container">
    <button id="btn_cancelar_venta">Cancelar</button>
    <button id="btn_registrar_venta">Pagar</button>
    <p id="subtotal_text">Subtotal: $0.00</p>
    <p id="iva_text">IVA (16%): $0.00</p>
    <p id="total_text">Total: $0.00</p>
  </div>
</div>

<div class="venta_modal" id="venta_modal">
  <h2>Ticket de venta</h2>
  <div class="ticket_list" id="ticket_list">
    <!-- Lista de productos se llenará aquí -->
  </div>
  <div class="totales">
    <div>Subtotal:</div> <div id="modal_subtotal">$0.00</div>
  </div>
  <div class="totales">
    <div>IVA (16%):</div> <div id="modal_iva">$0.00</div>
  </div>
  <div class="totales" style="font-size:18px;">
    <div><b>Total:</b></div> <div id="modal_total"><b>$0.00</b></div>
  </div>
  <form id="venta_form" method="post">
    {% csrf_token %}
    <button type="button" id="confirmar_venta">Confirmar Compra</button>
    <button type="button" id="cancelar_venta">Cancelar</button>
    <p id="success_message">Compra exitosa</p>
    <button type="button" id="btn_regresar">Regresar</button>
  </form>
</div>

<div class="facturacion_modal" id="facturacion_modal" style="display: none;">
  <h2>¿Deseas facturar esta compra?</h2>
  <button id="facturar_si">Sí</button>
  <button id="facturar_no">No</button>
</div>

<!-- Formulario de facturación -->
<div class="factura_form" id="factura_form" style="display: none;">
  <h3>Formulario de Facturación</h3>
  
  <label for="nombre">Nombre:</label>
  <input type="text" id="nombre" name="nombre" required>
  
  <label for="rfc">RFC:</label>
  <input type="text" id="rfc" name="rfc" required>
  
  <label for="direccion">Dirección:</label>
  <input type="text" id="direccion" name="direccion" required>
  
  <label for="correo">Correo Electrónico:</label>
  <input type="email" id="correo" name="correo" required>
  
  <label for="telefono">Teléfono:</label>
  <input type="tel" id="telefono" name="telefono" required>
  
  <label for="uso_cfdi">Uso del CFDI:</label>
  <select id="uso_cfdi" name="uso_cfdi" required>
    <option value="gastos_generales">Gastos en general</option>
    <option value="adquisicion_bienes">Adquisición de bienes</option>
    <option value="servicios">Servicios</option>
    <option value="otros">Otros</option>
  </select>
  
  <button type="submit" id="enviar_factura">Enviar</button>
</div>



<div class="modal_overlay" id="modal_overlay"></div>





{% endblock content %}

{% block scripts %}
<script>
  const registrarVentaUrl = "{% url 'ventas:registrar_venta_copy' %}";
</script>
<script src="{% static 'ventas/js/reg_venta.js' %}"></script>
<script src="{% static 'ventas/js/buscador_prod.js' %}"></script>
{% endblock scripts %}

ventas/templates/ventas/ventas.html
{% extends 'base.html' %}

{% block content %}

<h1>Ventas</h1>

<a href="{% url 'ventas:registrar_venta' %}">Registrar Venta</a>
<a href="{% url 'ventas:listar_ventas' %}">Listar Ventas</a>



{% endblock content %}