config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ventas/', include('ventas.urls')),
    path('inventario/', include('inventario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import signin, inicio

app_name = 'core'

urlpatterns = [
    path('', signin, name='signin'),
    path('inicio/', inicio, name='inicio'),   
]

ventas/urls.py
from django.urls import path
from .views import ventas, registrar_venta, listar_ventas, registrar_venta_copy
from . import views

app_name = 'ventas'

urlpatterns = [
    path('', ventas, name='ventas'),
    path('registrar/', registrar_venta, name='registrar_venta'),
    path('listar/', listar_ventas, name='listar_ventas'),
    path('registrar-copy/', registrar_venta_copy, name='registrar_venta_copy'),
]

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'img/logoTecno.jpeg' %}">
    {% comment %} <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Bungee+Spice&display=swap" rel="stylesheet"> {% endcomment %}

    <title>{% block title %}TecnoPlus{% endblock title %}</title>
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    <header>
        <nav class="sidebar">
            
            <ul>
                <li><a href="{% url 'core:inicio' %}">Inicio</a></li>
                <li><a href="{% url 'ventas:registrar_venta_copy' %}">Productos</a></li>
                <li><a href="{% url 'ventas:listar_ventas' %}">Historial de compras</a></li>
            </ul>
        </nav>
    </header>
    <section class="content">
        {% block content %}{% endblock content %}
    </section>
    {% block scripts %}{% endblock scripts %}
</body>
</html>

templates/sesion.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/sesion.css' %}">
    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
    {% block content %}{% endblock content %}

    <script src="{% static 'usuarios/js/sesion.js' %}"></script>
    {% block extra_scripts %}{% endblock extra_scripts %}
</body>
</html>