config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('ventas/', include('ventas.urls')),
    path('inventario/', include('inventario.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import signin, inicio

app_name = 'core'

urlpatterns = [
    path('', signin, name='signin'),
    path('inicio/', inicio, name='inicio'),   
]

usuarios/urls.py
from django.urls import path
from .views import usuarios, signin, registrar_usuario, lista_usuarios, signout

app_name = 'usuarios'

urlpatterns = [
    path('', usuarios, name='usuarios'),
    path('signin/', signin, name='signin'),
    path('registrar/', registrar_usuario, name='registrar_usuario'),
    path('lista/', lista_usuarios, name='lista_usuarios'),
    path('signout/', signout, name='signout'),
]

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Usuario(AbstractUser):
    
    telefono = models.CharField(max_length=20, blank=True)
    direccion = models.CharField(max_length=255, blank=True)
    primer_apellido = models.CharField(max_length=50)
    segundo_apellido = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.first_name} {self.primer_apellido} {self.segundo_apellido} ({self.get_rol_display()})"

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroUsuarioForm(UserCreationForm):
    class Meta:
        model = Usuario
        fields = ['first_name', 'primer_apellido', 'segundo_apellido', 'telefono', 'direccion', 'email', 'username', 'password1', 'password2']
        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'primer_apellido': 'Primer Apellido',
            'segundo_apellido': 'Segundo Apellido',
            'email': 'Correo Electrónico',
            'telefono': 'Teléfono',
            'direccion': 'Dirección',
            'password1': 'Contraseña',
            'password2': 'Confirmar Contraseña',
        }
        widgets = {
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'rol': forms.Select(attrs={'class': 'form-select'}),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from .forms import RegistroUsuarioForm
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.forms import AuthenticationForm

def usuarios(request):
    return redirect('usuarios:lista_usuarios')

def lista_usuarios(request):
    Usuario = get_user_model()
    usuarios = Usuario.objects.all()
    return render(request, 'usuarios/lista_usuarios.html', {'usuarios': usuarios})

def signin(request):
    if request.method == "GET":
        return render(request, 'usuarios/signin.html', {
            'form': AuthenticationForm
        })
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])

        if user is None:
            return render(request, 'usuarios/signin.html', {
                'form': AuthenticationForm,
                'error': 'Usuario o contraseña incorrectos'
            })
        else:
            login(request, user)
            return redirect('core:inicio')

def registrar_usuario(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = RegistroUsuarioForm(request.POST)
                if user.is_valid():
                    user.save()
                    return redirect('usuarios:lista_usuarios')
                else:
                    return render(request, 'usuarios/registrar_usuarios.html', {
                        'form': user,
                        'error': 'Por favor corrige los errores en el formulario.'
                    })
            except Exception as e:
                return render(request, 'usuarios/registrar_usuarios.html', {
                    'form': RegistroUsuarioForm(),
                    'error': f'Error inesperado: {str(e)}'
                })
            except IntegrityError:
                return render(request, 'usuarios/registrar_usuarios.html', {
                    'form': RegistroUsuarioForm(),
                    'error': 'Error de integridad: el usuario ya existe'
                })
            except ValueError:
                return render(request, 'usuarios/registrar_usuarios.html', {
                    'form': RegistroUsuarioForm(),
                    'error': 'Error de valor: los datos no son válidos'
                })
        else:   
            return render(request, 'usuarios/registrar_usuarios.html', {
                'form': RegistroUsuarioForm(),
                'error': 'Error de validación: Las contraseñas no coinciden'
            })
        
    else:
        return render(request, 'usuarios/registrar_usuarios.html', {
            'form': RegistroUsuarioForm()
        })
      
def signout(request):
    logout(request)
    return redirect('usuarios:signin')

usuarios/templates/usuarios/lista_usuarios.html
{% extends 'base.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'usuarios/css/lista.css' %}">
{% endblock extra_head %}

{% block content %}

<h2>Usuarios registrados</h2>

<div class="barra_sup">
    <input type="text" id="search" placeholder="Buscar usuario...">
    <a href="{% url 'usuarios:registrar_usuario' %}" class="reg_producto">Registrar otro usuario</a>
</div>

<div class="table_container">
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Correo</th>
                <th>Rol</th>

                
            </tr>
        </thead>
        <tbody>
            {% for usuario in usuarios %}
            <tr>
                <td>{{ usuario.username }}</td>
                <td>{{ usuario.email }}</td>
                <td>{{ usuario.rol }}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" class="no_products">No hay usuarios registrados</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<script>
  const searchInput = document.getElementById("search");
  const filas = document.querySelectorAll("tbody tr");

  searchInput.addEventListener("input", function () {
    const searchTerm = searchInput.value.toLowerCase();

    filas.forEach(fila => {
      const textoFila = fila.textContent.toLowerCase();
      if (textoFila.includes(searchTerm)) {
        fila.style.display = "";
      } else {
        fila.style.display = "none";
      }
    });
  });
</script>



{% endblock content %}

usuarios/templates/usuarios/registrar_usuarios.html
{% extends 'sesion.html' %}

{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'usuarios/css/registro.css' %}">
{% endblock extra_head %}


{% block content %}

<form method="post" class="registro-form">
  {% csrf_token %}
  
  <h2>Crear cuenta</h2>

  {{ error }}

  <p class="campo">
    {{ form.username.label_tag }}<br>
    {{ form.username }}
    {% if form.username.errors %}
      <ul class="error-list">
        {% for error in form.username.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.first_name.label_tag }}<br>
    {{ form.first_name }}
    {% if form.first_name.errors %}
      <ul class="error-list">
        {% for error in form.first_name.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.primer_apellido.label_tag }}<br>
    {{ form.primer_apellido }}
    {% if form.primer_apellido.errors %}
      <ul class="error-list">
        {% for error in form.primer_apellido.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.segundo_apellido.label_tag }}<br>
    {{ form.segundo_apellido }}
    {% if form.segundo_apellido.errors %}
      <ul class="error-list">
        {% for error in form.segundo_apellido.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.email.label_tag }}<br>
    {{ form.email }}
    {% if form.email.errors %}
      <ul class="error-list">
        {% for error in form.email.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.telefono.label_tag }}<br>
    {{ form.telefono }}
    {% if form.telefono.errors %}
      <ul class="error-list">
        {% for error in form.telefono.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.direccion.label_tag }}<br>
    {{ form.direccion }}
    {% if form.direccion.errors %}
      <ul class="error-list">
        {% for error in form.direccion.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.password1.label_tag }}<br>
    {{ form.password1 }}
    {% if form.password1.errors %}
      <ul class="error-list">
        {% for error in form.password1.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
  <p class="campo">
    {{ form.password2.label_tag }}<br>
    {{ form.password2 }}
    {% if form.password2.errors %}
      <ul class="error-list">
        {% for error in form.password2.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </p>
    
  <button type="submit">Crear cuenta</button>
  <button type="button" onclick="location.href='{% url 'usuarios:signin' %}'">Iniciar sesión</button>
  {% comment %} <button type="button" onclick="location.href="{% url 'usuarios:recuperar_contrasena' %}'">Recuperar contraseña</button>
  <button type="button" onclick="location.href="{% url 'usuarios:home' %}'">Volver a la página principal</button> {% endcomment %}
</form>


{% endblock content %}

usuarios/templates/usuarios/signin.html
{% extends 'sesion.html' %}

{% load static %}

{% block title %}Registro{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'usuarios/css/login.css' %}">
{% endblock extra_head %}

{% block content %}

<form method="post">
    <img src="{% static 'img/helmet-weights.png' %}" alt="Logo Gimnasio" class="logo">
    <h2>Inicio de Sesión</h2>

    {% csrf_token %}

    {% if error %}
    <p class="error">{{ error }}</p>
    {% endif %}
    {{ form }}
    <button>Iniciar Sesión</button>
    <button type="button" onclick="location.href='{% url 'usuarios:registrar_usuario' %}'">Crear una cuenta</button>
</form>

{% endblock content %}

{% block extra_scripts %}
{% endblock extra_scripts %}